-- RFID-Based Smart Attendance System
-- Final shared PostgreSQL schema for Team Zero Six.
-- Run this file only on a new, empty database.

BEGIN;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(id),
    code VARCHAR(30) NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_program_department_code UNIQUE (
        department_id,
        code
    ),
    CONSTRAINT uq_program_id_department UNIQUE (
        id,
        department_id
    )
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (
        role IN ('admin', 'teacher', 'staff', 'student')
    ),
    CONSTRAINT ck_users_status CHECK (
        status IN ('active', 'inactive', 'disabled')
    )
);

CREATE UNIQUE INDEX uq_users_username_ci
    ON users (LOWER(username));

CREATE UNIQUE INDEX uq_users_email_ci
    ON users (LOWER(email));

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    student_number VARCHAR(40) NOT NULL,
    registration_number VARCHAR(60) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    department_id BIGINT NOT NULL REFERENCES departments(id),
    program_id BIGINT NOT NULL,
    batch SMALLINT NOT NULL,
    academic_session VARCHAR(7) NOT NULL,
    semester VARCHAR(3) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_roll_scope UNIQUE (
        program_id,
        batch,
        student_number
    ),
    CONSTRAINT ck_students_batch CHECK (
        batch BETWEEN 1 AND 100
    ),
    CONSTRAINT ck_students_session CHECK (
        academic_session ~ '^[0-9]{4}-[0-9]{2}$'
    ),
    CONSTRAINT ck_students_semester CHECK (
        semester ~ '^[1-4]-[1-2]$'
    ),
    CONSTRAINT ck_students_status CHECK (
        status IN ('active', 'inactive', 'graduated', 'suspended')
    ),
    CONSTRAINT fk_students_program_department FOREIGN KEY (
        program_id,
        department_id
    ) REFERENCES programs(id, department_id)
);

CREATE UNIQUE INDEX uq_students_email_ci
    ON students (LOWER(email))
    WHERE email IS NOT NULL;

CREATE INDEX ix_students_program_batch
    ON students (program_id, batch);

CREATE INDEX ix_students_full_name_ci
    ON students (LOWER(full_name));

CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    employee_number VARCHAR(40) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    department_id BIGINT NOT NULL REFERENCES departments(id),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_teachers_status CHECK (
        status IN ('active', 'inactive')
    )
);

CREATE TABLE rfid_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid VARCHAR(128) NOT NULL,
    student_id BIGINT NOT NULL REFERENCES students(id),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    assigned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deactivated_at TIMESTAMPTZ,
    deactivation_reason VARCHAR(250),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_rfid_uid CHECK (
        uid = UPPER(uid)
        AND uid ~ '^[A-Z0-9]+$'
    ),
    CONSTRAINT ck_rfid_status CHECK (
        status IN (
            'active',
            'lost',
            'damaged',
            'replaced',
            'deactivated'
        )
    ),
    CONSTRAINT ck_rfid_deactivation CHECK (
        (status = 'active' AND deactivated_at IS NULL)
        OR
        (status <> 'active' AND deactivated_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_rfid_uid
    ON rfid_cards (uid);

-- A student can keep old card history but can have only one active card.
CREATE UNIQUE INDEX uq_rfid_one_active_card_per_student
    ON rfid_cards (student_id)
    WHERE status = 'active' AND deactivated_at IS NULL;

CREATE INDEX ix_rfid_student_id
    ON rfid_cards (student_id);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES programs(id),
    code VARCHAR(30) NOT NULL,
    title VARCHAR(160) NOT NULL,
    semester VARCHAR(3) NOT NULL,
    course_type VARCHAR(20) NOT NULL,
    credit_hours NUMERIC(4, 2) NOT NULL DEFAULT 3.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_courses_program_code UNIQUE (program_id, code),
    CONSTRAINT ck_courses_semester CHECK (
        semester ~ '^[1-4]-[1-2]$'
    ),
    CONSTRAINT ck_courses_type CHECK (
        course_type IN ('theory', 'practical')
    ),
    CONSTRAINT ck_courses_credit_hours CHECK (credit_hours > 0)
);

CREATE INDEX ix_courses_program_semester
    ON courses (program_id, semester);

CREATE TABLE course_offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id),
    teacher_id BIGINT NOT NULL REFERENCES teachers(id),
    academic_session VARCHAR(7) NOT NULL,
    batch SMALLINT NOT NULL,
    section VARCHAR(20) NOT NULL DEFAULT 'A',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_course_offering UNIQUE (
        course_id,
        academic_session,
        batch,
        section
    ),
    CONSTRAINT ck_offering_session CHECK (
        academic_session ~ '^[0-9]{4}-[0-9]{2}$'
    ),
    CONSTRAINT ck_offering_batch CHECK (
        batch BETWEEN 1 AND 100
    ),
    CONSTRAINT ck_offering_section_not_blank CHECK (
        BTRIM(section) <> ''
    ),
    CONSTRAINT ck_offering_status CHECK (
        status IN ('active', 'completed', 'cancelled')
    )
);

CREATE INDEX ix_course_offerings_teacher
    ON course_offerings (teacher_id, status);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id BIGINT NOT NULL
        REFERENCES course_offerings(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_enrollment UNIQUE (offering_id, student_id),
    CONSTRAINT ck_enrollment_status CHECK (
        status IN ('active', 'withdrawn', 'completed')
    )
);

CREATE INDEX ix_enrollments_student_id
    ON enrollments (student_id);

CREATE TABLE attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id BIGINT NOT NULL REFERENCES course_offerings(id),
    opened_by BIGINT NOT NULL REFERENCES users(id),
    scheduled_start TIMESTAMPTZ NOT NULL,
    scheduled_end TIMESTAMPTZ NOT NULL,
    attendance_opens_at TIMESTAMPTZ NOT NULL,
    attendance_closes_at TIMESTAMPTZ NOT NULL,
    late_after TIMESTAMPTZ NOT NULL,
    late_attendance_value NUMERIC(3, 2) NOT NULL,
    room VARCHAR(80),
    status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_session_schedule CHECK (
        scheduled_end > scheduled_start
    ),
    CONSTRAINT ck_session_attendance_window CHECK (
        attendance_closes_at > attendance_opens_at
    ),
    CONSTRAINT ck_session_late_time CHECK (
        late_after >= attendance_opens_at
        AND late_after <= attendance_closes_at
    ),
    CONSTRAINT ck_session_late_value CHECK (
        late_attendance_value BETWEEN 0.00 AND 1.00
    ),
    CONSTRAINT ck_session_status CHECK (
        status IN ('scheduled', 'open', 'closed', 'cancelled')
    )
);

CREATE INDEX ix_attendance_sessions_offering_start
    ON attendance_sessions (offering_id, scheduled_start);

CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL
        REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id),
    rfid_card_id BIGINT REFERENCES rfid_cards(id),
    status VARCHAR(20) NOT NULL,
    attendance_value NUMERIC(3, 2) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'rfid',
    scanned_at TIMESTAMPTZ,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    modified_at TIMESTAMPTZ,
    correction_reason VARCHAR(250),
    teacher_remark VARCHAR(250),
    CONSTRAINT uq_attendance_student_session UNIQUE (
        session_id,
        student_id
    ),
    CONSTRAINT ck_attendance_status CHECK (
        status IN (
            'present',
            'absent',
            'late',
            'fractional',
            'excused'
        )
    ),
    CONSTRAINT ck_attendance_value CHECK (
        attendance_value BETWEEN 0.00 AND 1.00
        AND (status <> 'present' OR attendance_value = 1.00)
        AND (status <> 'absent' OR attendance_value = 0.00)
    ),
    CONSTRAINT ck_attendance_source CHECK (
        source IN ('rfid', 'manual', 'imported', 'automatic')
    ),
    CONSTRAINT ck_attendance_modification CHECK (
        (modified_by IS NULL AND modified_at IS NULL)
        OR
        (modified_by IS NOT NULL AND modified_at IS NOT NULL)
    )
);

CREATE INDEX ix_attendance_records_student
    ON attendance_records (student_id, recorded_at DESC);

CREATE INDEX ix_attendance_records_session
    ON attendance_records (session_id);

CREATE TABLE attendance_correction_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_record_id BIGINT NOT NULL
        REFERENCES attendance_records(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id),
    reason VARCHAR(250) NOT NULL,
    evidence_url TEXT,
    requested_status VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewer_comment VARCHAR(250),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT ck_correction_reason_not_blank CHECK (
        BTRIM(reason) <> ''
    ),
    CONSTRAINT ck_correction_requested_status CHECK (
        requested_status IN (
            'present',
            'absent',
            'late',
            'fractional',
            'excused'
        )
    ),
    CONSTRAINT ck_correction_status CHECK (
        status IN ('pending', 'approved', 'rejected', 'cancelled')
    ),
    CONSTRAINT ck_rejected_request_has_comment CHECK (
        status <> 'rejected'
        OR BTRIM(COALESCE(reviewer_comment, '')) <> ''
    )
);

CREATE UNIQUE INDEX uq_one_pending_correction_per_record
    ON attendance_correction_requests (attendance_record_id)
    WHERE status = 'pending';

CREATE TABLE report_exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by BIGINT NOT NULL REFERENCES users(id),
    export_format VARCHAR(10) NOT NULL,
    filters JSONB NOT NULL DEFAULT '{}'::JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    filename VARCHAR(200),
    file_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT ck_report_export_format CHECK (
        export_format IN ('pdf', 'excel')
    ),
    CONSTRAINT ck_report_export_status CHECK (
        status IN ('pending', 'ready', 'failed')
    ),
    CONSTRAINT ck_ready_report_has_file CHECK (
        status <> 'ready'
        OR (
            BTRIM(COALESCE(filename, '')) <> ''
            AND BTRIM(COALESCE(file_path, '')) <> ''
            AND completed_at IS NOT NULL
        )
    )
);

CREATE INDEX ix_report_exports_requester_time
    ON report_exports (requested_by, created_at DESC);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    attendance_record_id BIGINT
        REFERENCES attendance_records(id) ON DELETE SET NULL,
    correction_request_id BIGINT
        REFERENCES attendance_correction_requests(id) ON DELETE SET NULL,
    report_export_id BIGINT
        REFERENCES report_exports(id) ON DELETE SET NULL,
    notification_type VARCHAR(40) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    deduplication_key VARCHAR(160),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    email_status VARCHAR(20) NOT NULL DEFAULT 'not_requested',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    CONSTRAINT ck_notification_type CHECK (
        notification_type IN (
            'attendance_confirmed',
            'attendance_updated',
            'attendance_rejected',
            'low_attendance',
            'correction_submitted',
            'correction_decided',
            'session_opened',
            'report_ready'
        )
    ),
    CONSTRAINT ck_notification_email_status CHECK (
        email_status IN ('not_requested', 'pending', 'sent', 'failed')
    ),
    CONSTRAINT ck_notification_read_time CHECK (
        (is_read = FALSE AND read_at IS NULL)
        OR
        (is_read = TRUE AND read_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_notifications_deduplication_key
    ON notifications (deduplication_key)
    WHERE deduplication_key IS NOT NULL;

CREATE INDEX ix_notifications_user_unread
    ON notifications (user_id, is_read, created_at DESC);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reset_token_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_password_reset_tokens_user
    ON password_reset_tokens (user_id, expires_at DESC);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    status VARCHAR(20) NOT NULL,
    ip_address INET,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_audit_status CHECK (
        status IN ('success', 'failed')
    )
);

CREATE INDEX ix_audit_logs_actor_time
    ON audit_logs (actor_user_id, created_at DESC);

CREATE INDEX ix_audit_logs_entity
    ON audit_logs (entity_type, entity_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_programs_updated_at
BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_teachers_updated_at
BEFORE UPDATE ON teachers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_rfid_cards_updated_at
BEFORE UPDATE ON rfid_cards
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_courses_updated_at
BEFORE UPDATE ON courses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_course_offerings_updated_at
BEFORE UPDATE ON course_offerings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_attendance_sessions_updated_at
BEFORE UPDATE ON attendance_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO departments (code, name)
VALUES ('CSE', 'Computer Science and Engineering');

INSERT INTO programs (department_id, code, name)
SELECT id, 'HONS', 'Honours'
FROM departments
WHERE code = 'CSE';

INSERT INTO programs (department_id, code, name)
SELECT id, 'MASTERS', 'Masters'
FROM departments
WHERE code = 'CSE';

INSERT INTO programs (department_id, code, name)
SELECT id, 'PHD', 'PhD'
FROM departments
WHERE code = 'CSE';

COMMIT;

